"""Mestá — major Slovak cities."""

MESTA = [
    "Bratislava",
    "Košice",
    "Prešov",
    "Nitra",
    "Žilina",
    "Banská Bystrica",
    "Trnava",
    "Trenčín",
    "Martin",
    "Poprad",
    "Zvolen",
    "Bardejov",
    "Levoča",
    "Komárno",
    "Spišská Nová Ves",
    "Liptovský Mikuláš",
    "Piešťany",
    "Ružomberok",
    "Banská Štiavnica",
    "Kežmarok",
    "Humenné",
    "Michalovce",
    "Topoľčany",
    "Lučenec",
    "Rimavská Sobota",
    "Rožňava",
    "Pezinok",
]

WIKIPEDIA = {
    "Martin": "Martin, Slovakia",
}

# Region (kraj) each city belongs to — used as the tag
KRAJE = {
    "Bratislava": "Bratislavský kraj",
    "Pezinok": "Bratislavský kraj",
    "Trnava": "Trnavský kraj",
    "Piešťany": "Trnavský kraj",
    "Trenčín": "Trenčiansky kraj",
    "Topoľčany": "Trenčiansky kraj",
    "Nitra": "Nitriansky kraj",
    "Komárno": "Nitriansky kraj",
    "Žilina": "Žilinský kraj",
    "Martin": "Žilinský kraj",
    "Liptovský Mikuláš": "Žilinský kraj",
    "Ružomberok": "Žilinský kraj",
    "Banská Bystrica": "Banskobystrický kraj",
    "Banská Štiavnica": "Banskobystrický kraj",
    "Zvolen": "Banskobystrický kraj",
    "Lučenec": "Banskobystrický kraj",
    "Rimavská Sobota": "Banskobystrický kraj",
    "Prešov": "Prešovský kraj",
    "Poprad": "Prešovský kraj",
    "Bardejov": "Prešovský kraj",
    "Levoča": "Prešovský kraj",
    "Kežmarok": "Prešovský kraj",
    "Humenné": "Prešovský kraj",
    "Košice": "Košický kraj",
    "Spišská Nová Ves": "Košický kraj",
    "Michalovce": "Košický kraj",
    "Rožňava": "Košický kraj",
}
