"""Zvieratá — native animals of Slovakia."""

ZVIERATA = [
    "Medveď hnedý",
    "Rys ostrovid",
    "Kamzík vrchovský tatranský",
    "Svišť tatranský",
    "Vlk dravý",
    "Zubor hrivnatý",
    "Vydra riečna",
    "Diviak lesný",
    "Jeleň lesný",
    "Srnec lesný",
    "Zajac poľný",
    "Hlucháň hôrny",
    "Tetrov hoľniak",
    "Orol skalný",
    "Bocian biely",
    "Bocian čierny",
    "Výr skalný",
    "Bobor vodný",
]

WIKIPEDIA = {
    "Medveď hnedý": "Brown bear",
    "Rys ostrovid": "Eurasian lynx",
    "Kamzík vrchovský tatranský": "Tatra chamois",
    "Svišť tatranský": "Tatra marmot",
    "Vlk dravý": "Eurasian wolf",
    "Zubor hrivnatý": "European bison",
    "Vydra riečna": "Eurasian otter",
    "Diviak lesný": "Wild boar",
    "Jeleň lesný": "Red deer",
    "Srnec lesný": "Roe deer",
    "Zajac poľný": "European hare",
    "Hlucháň hôrny": "Western capercaillie",
    "Tetrov hoľniak": "Black grouse",
    "Orol skalný": "Golden eagle",
    "Bocian biely": "White stork",
    "Bocian čierny": "Black stork",
    "Výr skalný": "Eurasian eagle-owl",
    "Bobor vodný": "Eurasian beaver",
}

# Latin scientific names — used as the tag
LATINSKE = {
    "Medveď hnedý": "Ursus arctos",
    "Rys ostrovid": "Lynx lynx",
    "Kamzík vrchovský tatranský": "Rupicapra rupicapra tatrica",
    "Svišť tatranský": "Marmota marmota latirostris",
    "Vlk dravý": "Canis lupus",
    "Zubor hrivnatý": "Bison bonasus",
    "Vydra riečna": "Lutra lutra",
    "Diviak lesný": "Sus scrofa",
    "Jeleň lesný": "Cervus elaphus",
    "Srnec lesný": "Capreolus capreolus",
    "Zajac poľný": "Lepus europaeus",
    "Hlucháň hôrny": "Tetrao urogallus",
    "Tetrov hoľniak": "Lyrurus tetrix",
    "Orol skalný": "Aquila chrysaetos",
    "Bocian biely": "Ciconia ciconia",
    "Bocian čierny": "Ciconia nigra",
    "Výr skalný": "Bubo bubo",
    "Bobor vodný": "Castor fiber",
}
